version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
    postBuild:
      commands:
        # index.html の $LIFFID を環境変数 LIFFID の値に置換
        - powershell -Command "(Get-Content dist\index.html) -replace '\$LIFFID', '$env:LIFFID' | Set-Content dist\index.html"
        # index.html の $PASSWORD を環境変数 PASSWORD の値に置換
        - powershell -Command "(Get-Content dist\index.html) -replace '\$PASSWORD', '$env:PASSWORD' | Set-Content dist\index.html"
  artifacts:
    baseDirectory: dist
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
